version: '3.3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env  

  db:
    image: postgres:15
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    command: -c max_connections=1000
    volumes:
      - supermarket_data:/var/lib/postgresql/data
    env_file:
      - .env  


volumes:
  supermarket_data: 
